### ISSUE TITLE
[Bug in SDK]: Space in the end of .github/ISSUE_TEMPLATE/config.yml

### ISSUE THREAD

**Issue by arsentos** [bitrix24/b24phpsdk#105]
### version(s) affected

1.1.0 < 

### Description

I've tried to fork this repository to help with issues and encoutered an error

> $ git clone https://github.com/bitrix24/b24phpsdk.git
Cloning into 'b24phpsdk'...
remote: Enumerating objects: 2919, done.
remote: Counting objects: 100% (254/254), done.
remote: Compressing objects: 100% (196/196), done.
remote: Total 2919 (delta 77), reused 79 (delta 51), pack-reused 2665 (from 2)
Receiving objects: 100% (2919/2919), 831.48 KiB | 4.49 MiB/s, done.
Resolving deltas: 100% (1490/1490), done.
error: invalid path '.github/ISSUE_TEMPLATE/config.yml '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

Looks like problem is space in the end of ".github/ISSUE_TEMPLATE/config.yml "file. It look like window-specific problem, as mentioned in this [stackoverflow question ](https://stackoverflow.com/questions/68133091/git-commands-fail-with-spaces-in-path)

### How to reproduce

Windows 11 Pro
Install git https://git-scm.com/downloads
Open Git Bash and execute  `git clone https://github.com/bitrix24/b24phpsdk.git` command

### Possible Solution

Simply remove space at the end of  '.github/ISSUE_TEMPLATE/config.yml ' :)

**Comment by arsentos** [comment]
Messed up with github, sry

**Comment by mesilov** [comment]
merged in dev branch, planned in 1.3.0 milestone to release
